sudo: false

language: node_js

node_js:
  - 6
  - 8
  - 9
  - 10
  - 12
  - 13

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 9
    - node_js: 13

before_install:
  # update NPM:
  - npm install -g npm
  - npm install -g mocha
  - npm --version
  - node --version

install:
  - npm install

script:
  - npm test